#version: '3.9'

services:
  web:
    build: .
    container_name: django_app
    env_file: .env
    ports:
      - "80:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: pg_db
    env_file: .env
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
  static_volume:
  media_volume:


# docker-compose up --build
# docker-compose exec web python manage.py migrate
# docker-compose exec web python manage.py createsuperuser
# pipreqs